version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: server
    volumes:
      - .:/app
    ports:
      - "8000:8080"
    env_file:
      - .env
    depends_on:
      - redis
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  redis:
    image: redis:6-alpine

  celery_worker:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: worker
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    command: flower
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "5557:5555"
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
