# Generated by Django 4.0.3 on 2022-03-21 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('github_projects', '0002_webhookconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectentry',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
